### ISSUE TITLE
libMyNativeSandBox.so?

### ISSUE THREAD

**Issue by yumin3** [Katana-O/MobileGamePenetrationTestingFramework#1]
libMyNativeSandBox.so?

**Comment by Katana-O** [comment]
That part is not open source , sorry.

**Comment by yumin3** [comment]
Hi bro,
how much would it cost to open source libMyNativeSandBox.so?

**Comment by yumin3** [comment]
@Katana-O 
Hi bro, 
how much would it cost to open source libMyNativeSandBox.so?

**Comment by Katana-O** [comment]
> @Katana-O Hi bro, how much would it cost to open source libMyNativeSandBox.so?

give me a price range, if you like.

**Comment by Katana-O** [comment]
> @Katana-O Hi bro, how much would it cost to open source libMyNativeSandBox.so?

You can discuss more detail with me via StaringTheWorldAtMyRearView123@protonmail.com, let me know when you sent mail.
